### ISSUE TITLE
Add options for setting PCU and PMU stages

### ISSUE THREAD

**Issue by kelayamatoz** [stanford-ppl/spade#1]
It would be nice to allow for manual configuration of # pipeline stages in PCU and PMU. I will create a pull request shortly

**Comment by kelayamatoz** [comment]
It seems that I don't have access to contribute to this repo. Here's a link to my fork: 
https://github.com/kelayamatoz/SpadeFork

All the changes are in SpadeConfig.scala and CUParams.scala. I just added two options to SpadeConfig and pass the option parameters to PCUParam and PMUParam

**Comment by yaqiz01** [comment]
the options are called pcu-stage and pmu-stage
